version: '3.8'

services:
  postgres:
    container_name: portfolio_postgres
    build:
      context: ./docker/postgres
    restart: always
    env_file:
      - dev.env
      - .env
      - postgres.env
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    container_name: portfolio_redis
    build:
      context: ./docker/redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis_volume
        target: ${WEB_CONTAINER_PATH}
        consistency: consistent
    networks:
      - backend

  web:
    container_name: portfolio_web
    build:
      dockerfile: ./docker/dev/web/Dockerfile
      context: .
    depends_on:
      - postgres
      - redis
    restart: always
    tty: true
    env_file:
      - dev.env
      - .env
      - postgres.env
    volumes:
      - type: volume
        source: web_volume
        target: ${WEB_CONTAINER_PATH}
        consistency: consistent
    ports:
      - "8001:8001"
      - "8890:8890"
    links:
      - redis:redis
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_volume:
  redis_volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/${WEB_HOST_PATH}
      o: bind
  web_volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/${WEB_HOST_PATH}
      o: bind