version: '3.7'

services:
  postgres:
    container_name: portfolio_postgres
    build:
      context: ./docker/prod/postgres
    restart: always
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - backend

  nginx:
    container_name: portfolio_nginx
    build:
      dockerfile: ./docker/prod/nginx/Dockerfile
      context: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/prod/nginx:/etc/nginx/conf.d
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    networks:
      - backend

  web:
    container_name: portfolio_web
    build:
      dockerfile: ./docker/prod/web/Dockerfile
      context: .
    depends_on:
      - postgres
      - nginx
    restart: on-failure
    env_file:
      - .env
      - prod.env
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    expose:
      - "8000"
    command:
      - gunicorn ab_back_end.wsgi:application --bind 0.0.0.0:8000 --workers=3
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_volume:
  static_volume:
  media_volume: