version: '3.8'

services:
  postgres:
    container_name: portfolio_postgres
    build:
      context: ./docker/postgres
    restart: always
    env_file:
      - prod.env
      - .env
      - postgres.env
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  web:
    container_name: portfolio_web
    build:
      dockerfile: ./docker/prod/web/Dockerfile
      context: .
    restart: on-failure
    env_file:
      - .env
      - prod.env
      - postgres.env
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    expose:
      - "80"
    command: gunicorn ab_back_end.wsgi --config docker/prod/gunicorn/conf.py
    depends_on:
      - postgres
    networks:
      - postgres_network
      - nginx_network

  nginx:
    container_name: portfolio_nginx
    build:
      dockerfile: ./docker/prod/nginx/Dockerfile
      context: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge

volumes:
  code_volume:
  postgres_volume:
  static_volume:
  media_volume: