version: '3.8'

services:
  postgres:
    container_name: portfolio_postgres
    build:
      context: ./docker/postgres
    restart: always
    env_file:
      - dev.env
      - .env
      - postgres.env
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    container_name: portfolio_web
    build:
      dockerfile: ./docker/dev/web/Dockerfile
      context: .
    depends_on:
      - postgres
    restart: always
    env_file:
      - dev.env
      - .env
      - postgres.env
    volumes:
      - type: volume
        source: web_volume
        target: ${WEB_CONTAINER_PATH}
        consistency: consistent
    ports:
      - "8001:8001"
      - "8890:8890"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_volume:
  web_volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/${WEB_HOST_PATH}
      o: bind