version: '3.7'

services:
  postgres_prod:
    container_name: portfolio_postgres_prod 
    build:
      context: ./docker/prod/postgres
    restart: always
    volumes:
      - type: volume
        source: postgres_vol_prod
        target: /var/lib/postgresql/data
    expose:
      - 5432

  nginx_prod:
    container_name: portfolio_nginx_prod
    build:
      dockerfile: ./docker/prod/nginx/Dockerfile
      context: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./docker/prod/nginx:/etc/nginx/conf.d
      - static_prod:/static
      - media_prod:/media

  web_prod:
    container_name: portfolio_web_prod
    build:
      dockerfile: ./docker/prod/web/Dockerfile
      context: .
    depends_on:
      - postgres_prod
      - nginx_prod
    restart: on-failure
    env_file:
      - .env
    volumes:
      - static_prod:/static
      - media_prod:/media
    expose:
      - 80

volumes:
  postgres_vol_prod:
  static_prod:
  media_prod: