version: '3.7'

services:
  postgres_prod:
    container_name: portfolio_postgres_prod 
    build:
      context: ./docker/prod/postgres
    restart: always
    volumes:
      - type: volume
        source: postgres_vol_prod
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - backend_prod

  nginx_prod:
    container_name: portfolio_nginx_prod
    build:
      dockerfile: ./docker/prod/nginx/Dockerfile
      context: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/prod/nginx:/etc/nginx/conf.d
      - static_prod:/static
      - media_prod:/media
    networks:
      - backend_prod

  web_prod:
    container_name: portfolio_web_prod
    build:
      dockerfile: ./docker/prod/web/Dockerfile
      context: .
    depends_on:
      - postgres_prod
      - nginx_prod
    restart: on-failure
    env_file:
      - .env
      - prod.env
    volumes:
      - static_prod:/static
      - media_prod:/media
    ports:
      - "8000:8000"
    networks:
      - backend_prod

networks:
  backend_prod:
    driver: bridge

volumes:
  postgres_vol_prod:
  static_prod:
  media_prod: