version: '3.8'

services:
  pg_test:
    image: ${COMPOSE_PROJECT_NAME}_pg_test_dev
    container_name: ${COMPOSE_PROJECT_NAME}_pg_test_dev
    build:
      context: ./docker/postgres/test
    env_file:
      - postgres.env
    tmpfs:
      - /var/lib/postgresql/data

  postgres:
    image: ${COMPOSE_PROJECT_NAME}_postgres_dev
    container_name: ${COMPOSE_PROJECT_NAME}_postgres_dev
    build:
      context: ./docker/postgres/dev
    restart: always
    env_file:
      - dev.env
      - .env
      - postgres.env
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    image: ${COMPOSE_PROJECT_NAME}_web_dev
    container_name: ${COMPOSE_PROJECT_NAME}_web_dev
    build:
      dockerfile: ./docker/dev/web/Dockerfile
      context: .
    depends_on:
      - postgres
    restart: always
    tty: true
    env_file:
      - dev.env
      - .env
      - postgres.env
    volumes:
      - .:/code
    ports:
      - "8001:8001"
      - "8890:8890"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_volume:
