version: '3.7'

services:
  postgres:
    container_name: portfolio_postgres
    build:
      context: ./docker/postgres  
    restart: always
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    expose:
      - 5432

  nginx:
    container_name: portfolio_nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./mediafiles:/media

  redis:
    container_name: portfolio_redis
    image: redis:latest
    restart: always
    expose:
      - 6379

  web:
    container_name: portfolio_web
    build: .
    depends_on:
      - postgres
      - nginx
    restart: on-failure
    env_file:
      - .env
    expose:
      - 8080:8080
    links:
      - postgres: postgres
      - redis: redis
    command: gunicorn --bind 0.0.0.0:8080 ab_back_end.wsgi