version: '3.7'

services:
  postgres:
    container_name: portfolio_postgres
    build:
      context: ./docker/prod/postgres
    restart: always
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - postgres_network

  web:
    container_name: portfolio_web
    build:
      dockerfile: ./docker/prod/web/Dockerfile
      context: .
    depends_on:
      - postgres
    restart: on-failure
    env_file:
      - .env
      - prod.env
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"
    networks:
      - nginx_network
      - postgres_network

  nginx:
    container_name: portfolio_nginx
    build:
      dockerfile: ./docker/prod/nginx/Dockerfile
      context: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/prod/nginx:/etc/nginx/conf.d
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge

volumes:
  postgres_volume:
  static_volume:
  media_volume: