version: '3.7'

services:
  postgres_dev:
    container_name: portfolio_postgres_dev
    build:
      context: ./docker/dev/postgres
    restart: always
    volumes:
      - type: volume
        source: postgres_vol_dev
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: 
      - backend

  pg_admin_dev:
    container_name: portfolio_pg_admin4_dev
    build:
      context: ./docker/dev/pg-admin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    depends_on:
      - postgres_dev
    ports:
      - 5050:5050
    networks:
      - backend

  web_dev:
    container_name: portfolio_web_dev
    build:
      dockerfile: ./docker/dev/web/Dockerfile
      context: .
    depends_on:
      - postgres_dev
      - pg_admin_dev
    restart: always
    env_file:
      - .env
    volumes:
      - type: volume
        source: web_vol_dev
        target: ${WEB_CONTAINER_PATH}
        consistency: consistent
    ports:
      - 8001:8001
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_vol_dev:
  web_vol_dev:
    driver: local
    driver_opts:
      type: none
      device: $PWD/${WEB_HOST_PATH}
      o: bind