version: '3.7'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: portfolio_db
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - backend
    ports:
      - 5432:5432

  db-admin:
    image: dpage/pgadmin4
    container_name: portfolio_db_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - backend

  web:
    build: .
    depends_on:
      - db
    restart_policy:
      - condition: on-failure
      - delay: 3s
      - max_attempts: 3
      - window: 150ms
    env_file:
      - .env
    container_name: portfolio_web
    networks:
      - backend
    command: sh /code/run-dev.sh
    ports:
      - 8001:8001
    volumes:
      - .:/code:cached

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: