[tool.pylint.MESSAGE_CONTROL]
disable = """
  line-too-long,
  missing-module-docstring,
  attribute-defined-outside-init,
"""

[tool.pylint.REPORTS]
reports = "no"

[tool.pylint.FORMAT]
max-line-length = "99"

[tool.pylint.BASIC]
good-names = "_,qs,pk"


[tool.black]
line-length = 99
skip-string-normalization = true
diff = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''


[tool.isort]
atomic = true
line_length = 89
include_trailing_comma = true
force_single_line = true
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true
default_section = "THIRDPARTY"
known_third_party = ["attr", "click", "py", "pytest", "setuptools", "tabulate"]
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
