# -- POETRY CONFIG ----------------------------------------------------------------------

[tool.poetry]
name = "portfolio"
version = "1.0.0"
description = "Portfolio"
authors = ["Wayne Lambert <wayne.a.lambert@gmail.com>"]

[tool.poetry.dependencies]
python = "==3.10.13"
django = "4.1.4"
djangorestframework = "==3.14.0"
django-crispy-forms = "==1.14.0"
django-recaptcha = "3.0.0"
django-widget-tweaks = "==1.4.12"
django-shapeshifter = "==18.9.23"
django-guardian = "==2.4.0"
django-axes = "==5.40.1"
django-storages = "==1.13.1"
django-ses = "==3.2.2"
django-filter = "==22.1"
django-tinymce = "==3.5.0"
django-bootstrap4 = "==22.3"
django-two-factor-auth = "==1.14.0"
psycopg2-binary = "2.9.5"
gunicorn = "==20.1.0"
whitenoise = "6.2.0"
requests = "==2.28.1"
beautifulsoup4 = "==4.11.1"
markdown = "==3.4.1"
boto3 = "1.26.29"
pygments = "==2.11.2"
pillow = "==9.3.0"
phonenumbers = "==8.13.2"
django-encrypted-model-fields = "0.6.5"
dj-database-url = "==1.2.0"
rich = "12.6.0"

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "3.8.1"
django-extensions = "3.2.1"
pytest = "7.2.0"
coverage = "6.5.0"
pytest-django = "4.5.2"
pytest-cov = "4.0.0"
pytest-factoryboy = "==2.5.1"
mixer = "7.2.2"
hypothesis = "6.61.0"
django-coverage-plugin = "3.0.0"
autopep8 = "1.6.0"
ptvsd = "==4.3.2"
bandit = "1.7.4"
interrogate = "1.5.0"
wily = "==1.24.0"
bpython = "0.23"
pylint = "2.15.8"
pylint-django = "2.5.3"
pycodestyle = "2.10.0"
ipdb = "==0.13.11"
ipython = "8.7.0"
pytest-randomly = "3.12.0"
pytest-vcr = "==1.0.2"
pdbpp = "0.10.3"
pytest-mock = "3.10.0"
pytest-xdist = "3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# -- PYLINT CONFIG ----------------------------------------------------------------------

[tool.pylint.master]
jobs = "0" # Auto-detect the number of processors
fail-under = "10"
ignore-patterns = '''
  \.eggs
  |_build
  |\.git
  |\.hg
  |\.mypy_cache
  |\.tox
  |\.venv
  |buck-out
  |build
  |conf.py
  |dist
'''
persistent = "no"
load-plugins = ["pylint_django"]
limit-inference-results = "100"
suggestion-mode = "yes"
unsafe-load-any-extension = "no"
extension-pkg-whitelist = ""
exit-zero = "no"
from-stdin = "no"

[tool.pylint.message_control]
enable = [
  "F", # Fatal
  "E", # Error
  "W", # Warning
  "R", # Refactor
  "C", # Convention
  "I", # Informational
]
disable = """
  attribute-defined-outside-init,
  line-too-long,
  missing-class-docstring,
  missing-function-docstring,
  missing-module-docstring,
  no-self-use,
"""

[tool.pylint.reports]
reports = "no"
msg-template = "{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}"
output-format = "colorized"
score = "no"

[tool.pylint.format]
max-line-length = "99"

[tool.pylint.basic]
good-names = "_, qs, pk"

[tool.pylint.miscellaneous]
notes = "TODO, FIXME, DEBUG, NOTE, DONE, TEMP BLOCK"

# -- BLACK CONFIG -----------------------------------------------------------------------

[tool.black]
line-length = 99
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

# -- ISORT CONFIG -----------------------------------------------------------------------

[tool.isort]
atomic = true
line_length = 99
profile = "black"
include_trailing_comma = true
force_single_line = false
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true
skip_glob = "*/.venv/*, */node_modules/*, */.git/*, */migrations/*"

sections = [
  "FUTURE",
  "STDLIB",
  "DJANGO",
  "THIRDPARTY",
  "FIRSTPARTY",
  "LOCALFOLDER",
]

known_django = "django"
known_third_party = [
  "PIL",
  "bs4",
  "captcha",
  "dj_database_url",
  "factory",
  "hypothesis",
  "mixer",
  "pytest",
  "requests",
  "rest_framework",
  "shapeshifter",
  "tinymce",
]

# -- PYTEST CONFIG ----------------------------------------------------------------------
[tool.pytest.ini_options]
minversion = "6.0"
django_find_project = true
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

addopts = [
  "--ds=aa_project.settings.pytest.pytest",
  "--reuse-db",
  "--nomigrations",
  "--fail-on-template-vars",
  "--doctest-modules",
  "--showlocals",
  "--strict-markers",
  "--ignore=.venv",
  "--cov=.",
  "--cov-report=html",
  "--randomly-dont-reorganize",
  "--numprocesses=auto",

  # Uses iPDB for `--trace` debugging
  "--pdbcls=IPython.terminal.debugger:TerminalPdb",
]

norecursedirs = [
  ".* build",
  "dist",
  "*.egg",
  "node_modules",
  "media",
  ".venv",
  "scss",
  "docs",
  ".git",
  "static",
  "staticfiles",
  "docker",
  "htmlcov",
]

testpaths = [
  "aa_project/tests",
  "apps/api/tests",
  "apps/blog/tests",
  "apps/contacts/tests",
  "apps/countdown_letters/tests",
  "apps/countdown_numbers/tests",
  "apps/cv/tests",
  "apps/pages/tests",
  "apps/roulette/tests",
  "apps/scraping/tests",
  "apps/text_analysis/tests",
  "apps/users/tests",
]

filterwarnings = ["ignore::django.utils.deprecation.RemovedInDjango50Warning"]

# Command Line Options
console_output_style = "progress"
log_cli = true
log_cli_level = "WARNING"
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

# Log Options
log_level = "INFO"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_format = "%(asctime)s %(levelname)s %(message)s"

# Log File Options
log_file = "logs/pytest/pytest_logs.log"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s %(levelname)s %(message)s"
log_file_date_format = "%Y-%m-%d %H:%M:%S"

# -- COVERAGE CONFIG --------------------------------------------------------------------

[tool.coverage]
[tool.coverage.run]
branch = true
parallel = true
source = ["."]
omit = [
  ".hypothesis/*",
  ".pytest_cache/*",
  ".venv/*",
  "*__init__.py",
  "*__pycache__",
  "*/aa_project/settings/dev.py",
  "*/aa_project/settings/pytest/pytest.py",
  "*/distutils/*",
  "*/node_modules/*",
  "*/site-packages/*",
  "*/static/*",
  "*/staticfiles/*",
  "*/tests/test*.py",
  "*/users/signals.py",
  "*admin.py*",
  "*apps.py",
  "*asgi.py",
  "*conftest.py",
  "*feeds.py",
  "*migrations/*",
  "*sitemap.py",
  "*wsgi.py",
  "manage.py",
]

[tool.coverage.report]
# fail_under = 95
skip_covered = false
show_missing = true
precision = 2
exclude_lines = [
  "def __repr__",
  "def __str__",
  "if __name__ == .__main__.:",
  "if 0:",
  "if DEBUG:",
  "if not DEBUG:",
  "if self.debug:",
  "if settings.DEBUG:",
  "pragma: no cover",
  "raise AssertionError",
  "raise NotImplementedError",
]
omit = ["venv/*", "tests/*", "setup.py", "*/__main__.py"]

# -- BANDIT CONFIG --------------------------------------------------------------------

[tool.bandit]
targets = ["/code/"]
exclude = [
  ".venv/*",
  "*apps.py",
  "*/migrations/*",
  "test_*.py",
  "*/node_modules/*",
  "./cacheback/*",
  "*/static/*",
  "*/staticfiles/*",
  "*/tests/test*.py",
  ".pytest_cache/*",
  ".hypothesis/*",
  "*wsgi.py",
  "*asgi.py",
  "manage.py",
  "*__init__.py",
  "*__pycache__",
  "*/site-packages/*",
  "*/distutils/*",
  "*/.git/*",
  ".github/*",
  "*/scss/*",
  "*/htmlcov/*",
  "*/logs/*",
  "*/media/*",
]
