[tool.black]
line-length = 99
skip-string-normalization = true
diff = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
atomic=true
force_single_line=true
lines_after_imports=2
lines_between_types=1
use_parentheses=true
known_first_party="interrogate"
known_third_party=["attr", "click", "py", "pytest", "setuptools", "tabulate"]

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-module = false
fail-under = 75
exclude = [
  ".git",
  ".mypy_cache",
  ".venv",
  "blog/migrations",
  "blog/admin.py"
]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*", ]
verbose = 2
quiet = false
whitelist-regex = []
color = true
