# -- PYLINT CONFIG ----------------------------------------------------------------------

[tool.pylint.master]
jobs="0"    # Auto-detect the number of processors
fail-under="10"
ignore-patterns='''
  \.eggs
  |_build
  |\.git
  |\.hg
  |\.mypy_cache
  |\.tox
  |\.venv
  |buck-out
  |build
  |conf.py
  |dist
'''
persistent="no"
load-plugins= ["pylint_django"]
limit-inference-results="100"
suggestion-mode="yes"
unsafe-load-any-extension="no"
extension-pkg-whitelist=""
exit-zero="no"
from-stdin="no"

[tool.pylint.message_control]
enable = [
  "F",  # Fatal
  "E",  # Error
  "W",  # Warning
  "R",  # Refactor
  "C",  # Convention
  "I",  # Informational
]
disable = """
  attribute-defined-outside-init,
  line-too-long,
  missing-class-docstring,
  missing-function-docstring,
  missing-module-docstring,
  no-self-use,
"""

[tool.pylint.reports]
reports = "no"
msg-template = "{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}"
output-format = "colorized"
score = "no"

[tool.pylint.format]
max-line-length = "99"

[tool.pylint.basic]
good-names = "_, qs, pk"

[tool.pylint.miscellaneous]
notes="TODO, FIXME, DEBUG"

# -- BLACK CONFIG -----------------------------------------------------------------------

[tool.black]
line-length = 99
skip-string-normalization = true
diff = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

# -- ISORT CONFIG -----------------------------------------------------------------------

[tool.isort]
atomic = true
line_length = 89
include_trailing_comma = true
force_single_line = false
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true
skip_glob = "*/.venv/*, */node_modules/*, */.git/*, */migrations/*"
known_django = "django"
known_third_party = ["PIL", "bs4", "captcha", "dj_database_url", "factory", "hypothesis", "mixer", "pytest", "requests", "rest_framework", "shapeshifter", "tinymce"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

# -- COVERAGE CONFIG --------------------------------------------------------------------

[tool.coverage]
  [tool.coverage.run]
    branch = true
    parallel = true
    source = ["."]
    omit = [
      ".hypothesis/*",
      ".pytest_cache/*",
      ".venv/*",
      "*__init__.py",
      "*__pycache__",
      "*/aa_project/settings/dev.py",
      "*/distutils/*",
      "*/node_modules/*",
      "*/site-packages/*",
      "*/static/*",
      "*/staticfiles/*",
      "*/tests/test*.py",
      "*/users/signals.py",
      "*aa_project/settings/pytest/pytest.py",
      "*aa_project/tests/factories",
      "*admin.py*",
      "*apps.py",
      "*asgi.py",
      "*conftest.py",
      "*feeds.py",
      "*migrations/*",
      "*sitemap.py",
      "*wsgi.py",
      "manage.py",
    ]

  [tool.coverage.report]
    # fail_under = 95
    skip_covered = true
    show_missing = true
    precision = 2
    exclude_lines = [
      "def __repr__",
      "def __str__",
      "if __name__ == .__main__.:",
      "if 0:",
      "if DEBUG:",
      "if not DEBUG:",
      "if self.debug:",
      "if settings.DEBUG:",
      "pragma: no cover",
      "raise AssertionError",
      "raise NotImplementedError",
    ]
    omit = [
      "venv/*",
      "tests/*",
      "setup.py",
      "*/__main__.py",
    ]
