name: PyTest and Coverage

on:
  push:
    branches:
      - "master"
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Run Tests and Generate Coverage Report
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install pytest-cov
          python -m pip install pytest-django
          python -m pip pytest-factoryboy
          python -m pip hypothesis
          pytest --runslow --cov=./ --cov-report=xml

      - name: Upload Coverage Report to Codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
