name: PyTest and Coverage

on:
  push:
    branches:
      - "master"

jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install PipEnv
        uses: dschep/install-pipenv-action@v1
        with:
          version: 2020.6.2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pipenv install --dev

      - name: Run Tests and Generate Coverage Report
        run: |
          pytest --runslow --cov=./ --cov-report=xml

      - name: Upload Coverage Report to Codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
